-- [테이블 생성]
-- 1. 
USE HR;

CREATE TABLE MEMBER (
MEMBER_ID INT PRIMARY KEY,
LAST_NAME VARCHAR(25) NOT NULL,
FIRST_NAME VARCHAR(25),
ADDRESS VARCHAR(100),
CITY VARCHAR(100),
PHONE VARCHAR(15),
JOIN_DATE DATETIME DEFAULT NOW() NOT NULL);

DESC MEMBER;

-- 2.
CREATE TABLE TITLE (
TITLE_ID INT PRIMARY KEY,
TITLE VARCHAR(60) NOT NULL,
DESCRIPTION VARCHAR(400) NOT NULL,
RATING VARCHAR(4) CHECK(RATING IN('G', 'PG', 'R', 'NC17', 'NR')),
CATEGORY VARCHAR(20) CHECK(CATEGORY IN('DRAMA', 'COMEDY', 'ACTION', 'CHILD', 'SCIFI', 'DOCUMENTARY')),
RELEASE_DATE DATE);

DESC TITLE;

CREATE TABLE TITLE_COPY (
COPY_ID INT,
TITLE_ID INT,
STATUS VARCHAR(15) CHECK(STATUS IN('AVAILABLE', 'DESTROYED', 'RENTED', 'RESERVED')),
FOREIGN KEY(TITLE_ID) REFERENCES TITLE(TITLE_ID),
constraint TITLE_COPY_PK PRIMARY KEY(COPY_ID, TITLE_ID));

DESC TITLE_COPY;

CREATE TABLE RENTAL (
BOOK_DATE DATETIME DEFAULT NOW(),
MEMBER_ID INT,
COPY_ID INT,
ACT_RET_DATE DATE,
EXP_RET_DATE DATE,
TITLE_ID INT,
FOREIGN KEY(MEMBER_ID) references MEMBER(MEMBER_ID),
FOREIGN KEY(COPY_ID, TITLE_ID) references TITLE_COPY(COPY_ID, TITLE_ID),
PRIMARY KEY(BOOK_DATE, MEMBER_ID, COPY_ID, TITLE_ID));

DESC RENTAL;

CREATE TABLE RESERVATION (
RES_DATE DATE,
MEMBER_ID INT,
TITLE_ID INT,
constraint RESERVATION_PK primary key(RES_DATE, MEMBER_ID, TITLE_ID),
FOREIGN KEY(MEMBER_ID) references MEMBER(MEMBER_ID),
FOREIGN KEY(TITLE_ID) references TITLE(TITLE_ID));

DESC RESERVATION;

